# Força Wayland nativo nos principais toolkits
MOZ_ENABLE_WAYLAND=1
QT_QPA_PLATFORM="wayland;xcb"
SDL_VIDEODRIVER=wayland

# Variáveis úteis em Compositores Wayland que
# não sejam ambientes desktop completos,
# pois nestes, dão problema: 
# GDK_BACKEND="wayland,x11"
# CLUTTER_BACKEND=wayland

# Suporte a apps Electron
ELECTRON_OZONE_PLATFORM_HINT=auto
NIXOS_OZONE_WL=1

# Correção para apps Java (essencial para Tiling WMs)
_JAVA_AWT_WM_NONREPARENTING=1
