MOZ_ENABLE_WAYLAND=1
SDL_VIDEODRIVER=wayland

# Variáveis úteis em Compositores Wayland que
# não sejam ambientes desktop completos,
# pois nestes, dão problema: 
# GDK_BACKEND="wayland,x11"
# CLUTTER_BACKEND=wayland
